version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./video_subtitles_convertor:/app
    command: >
      sh -c " python3 manage.py wait_for_db &&
              python3 manage.py migrate &&
              python3 manage.py runserver 0.0.0.0:8000"

    env_file:
      - ./settings.ini
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine3.20
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: supersecret
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A video_subtitles_convertor worker -l info
    volumes:
      - ./video_subtitles_convertor:/app
    env_file:
      - ./settings.ini
    depends_on:
      - db
      - redis
      - backend
volumes:
  pgdata:
